-- =============================================
-- Database Setup
-- =============================================

CREATE DATABASE newdatabase;
USE newdatabase;

-- View table
SELECT * FROM retail_sales;

-- Rename columns for clarity
ALTER TABLE retail_sales RENAME COLUMN months TO transaction_month;
ALTER TABLE retail_sales RENAME COLUMN years TO transaction_year;



-- =============================================
-- 1. What is the total revenue generated?
-- =============================================

SELECT SUM(total_amount) AS total_revenue
FROM retail_sales;

-- Business Insight:
-- This query calculates the total revenue generated by the business.
-- It helps evaluate the overall financial performance of the retail store.



-- =============================================
-- 2. Which product categories generate the most revenue?
-- =============================================

SELECT product_category,
SUM(total_amount) AS total_revenue
FROM retail_sales
GROUP BY product_category
ORDER BY total_revenue DESC;

-- Business Insight:
-- This query identifies which product categories contribute the most revenue.
-- High-performing categories can be prioritized for marketing campaigns and inventory planning.



-- =============================================
-- 3. Which customers contribute the highest revenue?
-- =============================================

SELECT customer_id,
SUM(total_amount) AS total_purchase
FROM retail_sales
GROUP BY customer_id
ORDER BY total_purchase DESC
LIMIT 30;

-- Business Insight:
-- Identifies the top customers based on total spending.
-- These high-value customers can be targeted with loyalty programs and personalized offers.



-- =============================================
-- 4. How do sales vary month by month?
-- =============================================

SELECT transaction_month,
SUM(total_amount) AS total_sales,
MONTHNAME(date) AS transaction_month_name
FROM retail_sales
GROUP BY transaction_month, transaction_month_name
ORDER BY transaction_month;

-- Business Insight:
-- Shows the monthly sales trend of the business.
-- Helps identify seasonal patterns and peak sales periods.



-- =============================================
-- 5. Which gender contributes the most revenue?
-- =============================================

SELECT gender,
SUM(total_amount) AS total_revenue
FROM retail_sales
GROUP BY gender;

-- Business Insight:
-- Determines which gender contributes more to total revenue.
-- Businesses can use this information for targeted marketing strategies.



-- =============================================
-- 6. Which product category sells the most units?
-- =============================================

SELECT product_category,
SUM(quantity) AS total_units_sold
FROM retail_sales
GROUP BY product_category
ORDER BY total_units_sold DESC;

-- Business Insight:
-- Identifies the most frequently purchased product categories.
-- Helps businesses understand customer demand and adjust inventory levels.



-- =============================================
-- 7. What is the total quantity sold and revenue generated by each category?
-- =============================================

SELECT product_category,
SUM(quantity) AS total_quantity,
SUM(total_amount) AS total_purchase_amount
FROM retail_sales
GROUP BY product_category
ORDER BY total_purchase_amount DESC;

-- Business Insight:
-- Shows both sales volume and revenue per category.
-- Useful for identifying categories that drive revenue vs categories with high purchase frequency.



-- =============================================
-- 8. Which product category is most purchased by each gender?
-- =============================================

SELECT gender,
product_category,
SUM(total_amount) AS total_amount
FROM retail_sales
GROUP BY gender, product_category
ORDER BY product_category;

-- Business Insight:
-- Helps understand purchasing preferences across genders.
-- Businesses can tailor marketing campaigns and product recommendations accordingly.



-- =============================================
-- 9. Which age group generates the highest revenue?
-- =============================================

SELECT 
CASE 
WHEN age < 25 THEN 'Young'
WHEN age BETWEEN 25 AND 40 THEN 'Adult'
WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'
ELSE 'Senior'
END AS age_group,
SUM(total_amount) AS total_sales
FROM retail_sales
GROUP BY age_group
ORDER BY total_sales DESC;

-- Business Insight:
-- Identifies which age segment contributes the most revenue.
-- This helps businesses focus marketing efforts on the most valuable customer segment.



-- =============================================
-- 10. How do product preferences vary by age group?
-- =============================================

SELECT 
CASE 
WHEN age < 25 THEN 'Young'
WHEN age BETWEEN 25 AND 40 THEN 'Adult'
WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'
ELSE 'Senior'
END AS age_group,
product_category,
COUNT(product_category) AS total_quantity,
SUM(total_amount) AS total_sales
FROM retail_sales
GROUP BY age_group, product_category
ORDER BY total_sales DESC;

-- Business Insight:
-- Analyzes how product preferences differ across age groups.
-- Helps businesses target specific products to different customer demographics.



-- =============================================
-- 11. Which customers are the highest spenders?
-- (Using Window Function Ranking)
-- =============================================

SELECT 
customer_id,
SUM(total_amount) AS total_spending,
DENSE_RANK() OVER (ORDER BY SUM(total_amount) DESC) AS customer_rank
FROM retail_sales
GROUP BY customer_id;

-- Business Insight:
-- Ranks customers based on their spending.
-- Helps identify VIP customers and potential candidates for loyalty programs.



-- =============================================
-- 12. Which product category performs best within each age group?
-- =============================================

SELECT 
age_group,
product_category,
COUNT(product_category) AS total_quantity,
SUM(total_amount) AS total_sales,
DENSE_RANK() OVER(PARTITION BY age_group ORDER BY SUM(total_amount) DESC) AS rank_within_age_group
FROM (
SELECT 
CASE 
WHEN age < 25 THEN 'Young'
WHEN age BETWEEN 25 AND 40 THEN 'Adult'
WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'
ELSE 'Senior'
END AS age_group,
product_category,
total_amount
FROM retail_sales
) t
GROUP BY age_group, product_category
ORDER BY age_group, total_sales DESC;

-- Business Insight:
-- Identifies the most popular product categories for each age group.
-- Helps businesses personalize product recommendations and marketing campaigns.



-- =============================================
-- 13. What percentage of total revenue does each category contribute?
-- =============================================

SELECT 
product_category,
SUM(total_amount) AS category_sales,
ROUND(
SUM(total_amount) * 100 / SUM(SUM(total_amount)) OVER(),2
) AS revenue_percentage
FROM retail_sales
GROUP BY product_category
ORDER BY category_sales DESC;

-- Business Insight:
-- Calculates the revenue contribution percentage of each product category.
-- Helps businesses identify which categories drive the majority of revenue.



-- =============================================
-- 14. Which product category performs best for each age segment?
-- (Using CTE)
-- =============================================

WITH age_group_sales AS (
SELECT
CASE
WHEN age < 25 THEN 'Young'
WHEN age BETWEEN 25 AND 40 THEN 'Adult'
WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'
ELSE 'Senior'
END AS age_group,
product_category,
SUM(total_amount) AS total_sales
FROM retail_sales
GROUP BY age_group, product_category
)

SELECT *
FROM age_group_sales
ORDER BY age_group, total_sales DESC;

-- Business Insight:
-- Provides a clearer view of category performance within each age segment.
-- Useful for demographic-based marketing strategies.



-- =============================================
-- 15. Which customer demographic drives revenue for each category?
-- =============================================

SELECT 
a.product_category,
b.age_group,
SUM(a.total_amount) AS total_sales
FROM retail_sales a
JOIN (
    SELECT 
    customer_id,
    CASE
    WHEN age < 25 THEN 'Young'
    WHEN age BETWEEN 25 AND 40 THEN 'Adult'
    WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'
    ELSE 'Senior'
    END AS age_group
    FROM retail_sales
) b
ON a.customer_id = b.customer_id
GROUP BY a.product_category, b.age_group
ORDER BY a.product_category, total_sales DESC;

-- Business Insight:
-- Identifies which age group contributes the most revenue within each product category.
-- Helps optimize marketing strategies for specific demographics.



-- =============================================
-- 16. Analyze monthly sales trends and category rankings
-- =============================================

SELECT
product_category,
transaction_month,
SUM(total_amount) AS monthly_sales,

LAG(SUM(total_amount)) 
OVER(PARTITION BY product_category ORDER BY transaction_month) AS prev_month_sales,

LEAD(SUM(total_amount)) 
OVER(PARTITION BY product_category ORDER BY transaction_month) AS next_month_sales,

ROW_NUMBER() 
OVER(PARTITION BY product_category ORDER BY SUM(total_amount) DESC) AS row_no,

RANK() 
OVER(PARTITION BY product_category ORDER BY SUM(total_amount) DESC) AS sales_rank,

DENSE_RANK() 
OVER(PARTITION BY product_category ORDER BY SUM(total_amount) DESC) AS dense_ranking

FROM retail_sales
GROUP BY product_category, transaction_month
ORDER BY product_category, transaction_month;

-- Business Insight:
-- This query analyzes monthly sales trends and ranks months based on sales performance.
-- Window functions help track changes in sales across months and identify peak sales periods.